### PR TITLE
Use relative protocol rather than fixed for basePath

### PR DESCRIPTION
**Pull request by billinghamj**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@billinghamj Thank you for the pull request. Could you please explain what problem/use case are you trying to solve? I am not sure if a protocol-relative URL is valid according to Swagger specification, have you checked the spec?

@shelbys the hardcoded protocol was added to support your use case via #62. Will the implementation proposed here work for you too?

**Comment by bajtos** [comment]
EDIT:  the hardcoded protocol was added via #61, not #62.

**Comment by shelbys** [comment]
@bajtos - We've long-since been using `x-forwarded-proto` in our fork, so this change makes sense to me.  See: https://github.com/shelbys/loopback-explorer/blob/master/lib/swagger.js#L119

**Comment by billinghamj** [comment]
@bajtos The problem for us is when doing reverse proxying, via a system we don't have control over, the x-forwarded-proto header is not correctly set. When we browse to the explorer, the URLs are not correctly generated.

Relative protocols will work in all cases - based on the current browser context.

**Comment by bajtos** [comment]
@billinghamj I see, it makes sense. I am still reluctant to land this patch as it is, as I am concerned that it may break backwards compatibility.

I am proposing the following solution that should allow you to implement what you need, while preserving current behaviour for existing users:

```js
var proto = opts.omitProtocolInBaseUrl  ?  '//' :
  (headers['x-forwarded-proto'] || opts.protocol || req.protocol) + '://';
var host = headers['x-forwarded-host'] || headers.host;
doc.basePath = proto + host + initialPath;
```

Usage

```js
app.use('/explorer', explorer(app, { omitProtocolInBaseUrl: true }));
```

Thoughts?

I'll also need you to add a unit-test to verify the new behaviour, see the existing tests for inspiration: https://github.com/strongloop/loopback-explorer/blob/ccfd9c42b08e30e8ea6564735827940c519db308/test/swagger.test.js#L73-L107

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode test please

**Comment by billinghamj** [comment]
Yes that works for me.

**Comment by bajtos** [comment]
> Yes that works for me.

@billinghamj great! could you then update the pull request please?

**Comment by bajtos** [comment]
Closing in favour of #102.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request closed without merging**
